### ISSUE TITLE
IT8951 

### ISSUE THREAD

**Issue by esariyev** [philipplive/IT8951-USB#1]
Hallo, können wir mit USB 12 Stück IT8951 Board für die Anzeige verschiedener Bilder verwenden?

**Comment by philipplive** [comment]
when you have 12 usb ports, you can adress each board separat.

best regards

**Comment by esariyev** [comment]
I am using raspberry pi own operation system can you say me how i can run
your code then i can solve my problem about 12 output. Thank you very much.

**Comment by philipplive** [comment]
you see in the manual an exactly description how you can compile the file, and how to address a individual usb-port (e.g. with "/dev/sg0") from the raspberry pi.

**Comment by esariyev** [comment]
Thank you very much.Last question this code suatble for raspery own
operation system ? or i must ubload other os like ubuntu etc?

**Comment by philipplive** [comment]
I use it on "Raspberry Pi OS Lite" (debian). I think it should run on every Linux based OS.
Give me a feedback when it works with another display-size or OS :-)

**Comment by esariyev** [comment]
Okay i am working 13.3 inch and 7.8 inch.i will share pictures.Thank you
very much.

**Comment by esariyev** [comment]
![165149801_811370346128633_2763557794001088897_n](https://user-images.githubusercontent.com/52784706/112488644-04bfb380-8d7e-11eb-8ce8-2a84f54b1671.jpg)

what is problem?

**Comment by philipplive** [comment]
i think to use the usb-port, you must run the program as root.

**Comment by esariyev** [comment]
How i can do it? My knowledge is poor for raspberry pi.

**Comment by philipplive** [comment]
you found documentation about this on the raspberry website (https://www.raspberrypi.org/documentation/linux/usage/root.md)

**Comment by esariyev** [comment]
Thank i solved problem.But what is convert function we must install
externall library for it ? it is nesserary

**Comment by philipplive** [comment]
"convert" is a function from "imagemagick", you can easy install this on your raspberry-pi.
